#!/bin/bash
#PBS -l nodes=1:ppn=1,walltime=0:05:00
#PBS -N app-MakeMIDGainLossStimFiles

echo "Running MakeMIDGainLossStimFiles App"
singularity exec -e docker://brainlife/fsl:5.0.9 ./MakeMIDGainLossStimFiles.sh
